import pytest

from tests.factories.DataFactories import (
    QuestionYamlFactory,
)

from blueprint_forge import (
    Question,
    QuestionCollection,
    EmptyQuestionCollection,
    InvalidPrerequisites,
    DuplicateQuestionID,
)

def make_question(question_yaml) -> Question:
    question_id, question_data = next(iter(question_yaml.items()))
    
    return Question.from_dict(
        id=question_id,
        data=question_data
        )

@pytest.mark.parametrize(
    "data",
    [
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        prerequisites=[],
                        )
                )
            ],
            id="collection_containing_one_Question",    
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1", "node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=[],
                    )
                ),
            ],
            id="collection_containing_multiple_Questions",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1", "node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=[],
                    )
                ),
            ],
            id="all_prerequisite_references_resolve",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=[],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=["node_1"],
                    )
                ),
            ],
            id="no_prerequisite_cycles",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=[],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=[],
                    )
                ),
            ],
            id="self-references_absent",
        ),
    ]
)

def test_QuestionCollection_accepts_valid_data(data):
    QuestionCollection(questions=data)

@pytest.mark.parametrize(
    "data, expected_exception",
    [
        pytest.param(
            [],
            EmptyQuestionCollection,
            id="empty_collection",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_3"]
                    )
                )
            ],
            InvalidPrerequisites,
            id="unknown_prerequisite",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=[],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=[],
                    )
                ),
            ],
            DuplicateQuestionID,
            id="duplicate_question_id",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_0"]
                    )
                )
            ],
            InvalidPrerequisites,
            id="self-referential_prerequisite",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_0"],
                    )
                ),
            ],
            InvalidPrerequisites,
            id="single-element_prerequisites_A-B-A_cycle",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=["node_3"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_3",
                        prerequisites=["node_0"],
                    )
                ),
            ],
            InvalidPrerequisites,
            id="single-element_prerequisites_A-B-C-A_cycle",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=["node_3"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_3",
                        prerequisites=["node_2"],
                    )
                ),
            ],
            InvalidPrerequisites,
            id="single-element_prerequisites_A-B-C-B_cycle",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2", "node_3"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=[],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_3",
                        prerequisites=["node_0"],
                    )
                ),
            ],
            InvalidPrerequisites,
            id="nested_multi-element_prerequisite_A-B-C-A_cycle",
        ),
        pytest.param(
            [
                make_question(
                    QuestionYamlFactory(
                        id="node_0",
                        prerequisites=["node_1"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_1",
                        prerequisites=["node_2", "node_3"],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_2",
                        prerequisites=[],
                    )
                ),
                make_question(
                    QuestionYamlFactory(
                        id="node_3",
                        prerequisites=["node_1"],
                    )
                ),
            ],
            InvalidPrerequisites,
            id="nested_multi-element_prerequisite_A-B-C-B_cycle",
        ),
    ]
)

def test_QuestionCollection_rejects_invalid_data(data, expected_exception):
    with pytest.raises(expected_exception) as exc_info:
        QuestionCollection(questions=data)